project:
  type: website

website:
  title: "Research notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css
    date-format: "MMMM, YYYY"

editor: visual

